### ISSUE TITLE
[BUG] - google.api_core.exceptions.MethodNotImplemented: 501 Received http2 header with status: 404

### ISSUE THREAD

**Issue by sandeep2sky** [mesmacosta/datacatalog-util#9]
**What happened**:
I ran the datacatalog-util in GCP Cloud shell and it throw exception below:
It is throwing below error while running on GCP Cloud Shell.
Could you please help me to resolve it.

Error Log=============

status = StatusCode.UNIMPLEMENTED
details = "Received http2 header with status: 404"
debug_error_string = "{"created":"@1616126950.574176093","description":"Received http2 :status header with non-200 OK status","file":"src/core/ext/filters/http/client/http_client_filter.cc","file_line":129,"grpc_message":"Received http2 header with sta
tus: 404","grpc_status":12,"value":"404"}"

**What you expected to happen**:
Ideally it should start updating the Dataset table in Data Catalog based in the .csv file data

**How to reproduce it (as minimally and precisely as possible)**:
Create GCP project and service account with needed permissions.
Run as the guide document described
**Anything else we need to know?**:

**Comment by mesmacosta** [comment]
Hi @sandeep2sky, thanks for opening this!

I'm here to help, could you provide me more information about the issue?

1. What command did you try to execute?
Was it the `datacatalog-util tags create --csv-file CSV_FILE_PATH` command?

2. Did you follow the sample-input, like: [tags-opt-1-all-metadata.csv](https://github.com/mesmacosta/datacatalog-util/blob/master/sample-input/create-tags/tags-opt-1-all-metadata.csv)?

From the error message, I'd guess that the Data Catalog client library is not able to find the entry to update the tags, this might be something invalid in the CSV file, like the `linked_resource`.... Do you also have created the tag template before?

Some context: I just ran the create tags tutorial with a new table at:
[create-the-tags](https://github.com/mesmacosta/datacatalog-util#22-run-the-datacatalog-util-script---create-the-tags), and was able to successfully execute it.

Are you using the default Big Query location or some specific region in your table/dataset? To help me troubleshoot this.

**Comment by mesmacosta** [comment]
This is linked to issue: https://github.com/ricardolsmendes/datacatalog-tag-manager/issues/39

**Comment by mesmacosta** [comment]
@ricardolsmendes to be aware.

**Comment by sandeep2sky** [comment]
Thanks @mesmacosta @ricardolsmendes. The issue got resolved. It was due to csv file. I was using csv file that I have saved  from an Excel file in the predefined format. I tried to use the CSV from the GitHub provided in the package itself and it resolved the issue. Layout and content was same but it works with csv from repo. Thanks for your support and comment.

**Comment by mesmacosta** [comment]
thanks @sandeep2sky !
